// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CalendarController from "./calendar_controller";
import { Toggle, Modal, Dropdown } from "tailwindcss-stimulus-components";

application.register('dropdown', Dropdown);
application.register('modal', Modal);
application.register("calendar", CalendarController);
application.register('toggle', Toggle);